FROM node:lts AS build

WORKDIR /usr/src/app
COPY . .

RUN npm i
RUN npm run build:api

FROM node:lts-alpine AS production

WORKDIR /usr/src/app

COPY --from=build /usr/src/app/package.json .
COPY --from=build /usr/src/app/package-lock.json .
COPY --from=build /usr/src/app/dist ./dist
COPY --from=build /usr/src/app/patches ./patches
COPY --from=build /usr/src/app/config ./config
RUN npm i --omit=dev

EXPOSE 9056

CMD ["node", "dist/api.js"]